# bc250-encoding-decoding-fix v0.5.2 - https://github.com/simpmix/bc250-encoding-decoding-fix
PACKAGE_NAME="bc250-audio-fix"
PACKAGE_VERSION="0.5.2"
CLEAN="make clean"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="bc250_audio_fix"
DEST_MODULE_LOCATION[0]="/kernel/drivers/sound"
AUTOINSTALL="yes"
